#!/usr/bin/env node
// @ts-check

import { randomUUID } from 'node:crypto';
import { appendFileSync, closeSync, existsSync, fsyncSync, linkSync, lstatSync, mkdirSync, openSync, readFileSync, readdirSync, realpathSync, renameSync, unlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { ContractError, canonicalJson, envelopeDigest, parseJsonStrict, sha256, validateContract } from './contract-tool.mjs';

const SKILL_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const NODE_STATES = new Set(['pending', 'running', 'blocked', 'awaiting_verification', 'passed', 'failed', 'cancelled']);
const TERMINAL_NODE_STATES = new Set(['passed', 'failed', 'cancelled']);
export class LedgerError extends Error {}

function readJson(path) { return parseJsonStrict(readFileSync(path, 'utf8')); }
function atomicJson(path, value) { const temp = `${path}.${process.pid}.${randomUUID()}.tmp`; writeFileSync(temp, `${JSON.stringify(value, null, 2)}\n`, { flag: 'wx', mode: 0o600 }); renameSync(temp, path); }
function writeNew(path, value) { writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, { flag: 'wx', mode: 0o600 }); }
function alive(pid) { try { process.kill(pid, 0); return true; } catch (error) { return Boolean(error?.code === 'EPERM'); } }
function recoverReclaim(path) { const reclaimPath = `${path}.reclaim`; if (!existsSync(reclaimPath)) return; let owner; try { owner = readJson(reclaimPath); } catch { throw new LedgerError('ledger reclaim lock malformed；拒绝自动接管'); } if (!Number.isInteger(Number(owner.pid)) || Number(owner.pid) <= 0 || typeof owner.token !== 'string' || !owner.token) throw new LedgerError('ledger reclaim owner 无效；拒绝自动接管'); if (alive(Number(owner.pid))) throw new LedgerError('ledger lock stale recovery in progress'); let latest; try { latest = readJson(reclaimPath); } catch (error) { if (error?.code === 'ENOENT') return; throw new LedgerError('ledger reclaim lock malformed；拒绝自动接管'); } if (Number(latest.pid) !== Number(owner.pid) || latest.token !== owner.token) return; try { unlinkSync(reclaimPath); } catch (error) { if (error?.code !== 'ENOENT') throw error; } }
function lock(path) {
  for (let attempt = 0; attempt < 4; attempt += 1) {
    recoverReclaim(path);
    const owner = { pid: process.pid, token: randomUUID(), acquired_at: new Date().toISOString() }; const candidate = `${path}.${owner.pid}.${owner.token}.candidate`; const fd = openSync(candidate, 'wx', 0o600); try { writeFileSync(fd, `${JSON.stringify(owner)}\n`); fsyncSync(fd); } finally { closeSync(fd); }
    try { if (existsSync(`${path}.reclaim`)) throw new LedgerError('ledger lock stale recovery in progress'); linkSync(candidate, path); unlinkSync(candidate); return owner; }
    catch (error) { try { unlinkSync(candidate); } catch {} if (error instanceof LedgerError) throw error; if (error?.code !== 'EEXIST') throw error; let current; try { current = readJson(path); } catch { throw new LedgerError('ledger lock malformed；拒绝自动接管'); } if (!Number.isInteger(Number(current.pid)) || Number(current.pid) <= 0) throw new LedgerError('ledger lock owner 无效；拒绝自动接管'); if (alive(Number(current.pid))) throw new LedgerError(`ledger lock held by ${current.pid}`); const reclaimPath = `${path}.reclaim`; const reclaimOwner = { pid: process.pid, token: randomUUID(), acquired_at: new Date().toISOString() }; const reclaimCandidate = `${reclaimPath}.${reclaimOwner.pid}.${reclaimOwner.token}.candidate`; const reclaimFd = openSync(reclaimCandidate, 'wx', 0o600); try { writeFileSync(reclaimFd, `${JSON.stringify(reclaimOwner)}\n`); fsyncSync(reclaimFd); } finally { closeSync(reclaimFd); } try { linkSync(reclaimCandidate, reclaimPath); } catch (reclaimError) { if (reclaimError?.code !== 'EEXIST') throw reclaimError; throw new LedgerError('ledger lock stale recovery in progress'); } finally { try { unlinkSync(reclaimCandidate); } catch {} } try { let latest; try { latest = readJson(path); } catch (latestError) { if (latestError?.code === 'ENOENT') continue; throw new LedgerError('ledger lock malformed；拒绝自动接管'); } if (Number(latest.pid) !== Number(current.pid) || latest.token !== current.token) continue; if (alive(Number(latest.pid))) throw new LedgerError(`ledger lock held by ${latest.pid}`); unlinkSync(path); } finally { release(reclaimPath, reclaimOwner); } }
  }
  throw new LedgerError('无法获取 ledger lock');
}
function release(path, owner) { let current; try { current = readJson(path); } catch (error) { if (error?.code === 'ENOENT') return false; throw new LedgerError('ledger lock 在持有期间损坏；拒绝删除未知 owner 的 lock'); } if (current.pid !== owner.pid || current.token !== owner.token) return false; unlinkSync(path); return true; }
function withLock(dir, callback) { const path = join(dir, '.lock'); const owner = lock(path); try { return callback(); } finally { release(path, owner); } }
function manifest(root) { const files = []; const visit = (absolute, rel) => { const stat = lstatSync(absolute); if (stat.isDirectory()) for (const name of readdirSync(absolute).sort()) visit(join(absolute, name), rel ? `${rel}/${name}` : name); else if (stat.isFile() || stat.isSymbolicLink()) { const bytes = readFileSync(absolute); files.push({ path: rel, size: bytes.length, sha256: sha256(bytes) }); } }; for (const name of ['SKILL.md', 'agents', 'references', 'scripts']) if (existsSync(join(root, name))) visit(join(root, name), name); return files.sort((a, b) => a.path.localeCompare(b.path)); }
export function skillContentDigest(root = SKILL_ROOT) { return sha256(Buffer.from(canonicalJson(manifest(realpathSync(root))), 'utf8')); }
function future(path) { let cursor = resolve(path); const suffix = []; while (!existsSync(cursor)) { const parent = dirname(cursor); if (parent === cursor) break; suffix.unshift(cursor.slice(parent.length + 1)); cursor = parent; } return resolve(realpathSync(cursor), ...suffix); }
function inside(candidate, parent) { const rel = relative(realpathSync(parent), future(candidate)); return rel === '' || (!rel.startsWith(`..${sep}`) && rel !== '..' && !isAbsolute(rel)); }

function readJournal(dir) {
  const text = readFileSync(join(dir, 'events.ndjson'), 'utf8'); const last = text.lastIndexOf('\n'); const complete = last < 0 ? '' : text.slice(0, last + 1); const trailing = last === text.length - 1 ? '' : text.slice(last + 1);
  const events = complete.split('\n').filter(Boolean).map(parseJsonStrict); if (!events.length) throw new LedgerError('ledger journal 为空'); let previous = null; for (let index = 0; index < events.length; index += 1) { const event = events[index]; if (event.revision !== index || event.previous_event_digest !== previous || !/^sha256:[0-9a-f]{64}$/u.test(event.event_digest ?? '') || envelopeDigest(event, 'event_digest') !== event.event_digest) throw new LedgerError(`event journal 链在 revision ${index} 无效`); previous = event.event_digest; } return { events, complete, trailing };
}
function load(dir) { const journal = readJournal(dir); const latest = journal.events.at(-1).snapshot; const path = join(dir, 'snapshot.json'); if (!existsSync(path)) return { snapshot: latest, repair: true, journal }; const file = readJson(path); const drift = canonicalJson(file) !== canonicalJson(latest); return { snapshot: drift ? latest : file, repair: drift || Boolean(journal.trailing), journal }; }
function persist(dir, snapshot, kind) { const next = { ...snapshot, revision: snapshot.revision + 1, updated_at: new Date().toISOString() }; const previous = readJournal(dir).events.at(-1)?.event_digest ?? null; const event = { schema_version: 1, revision: next.revision, kind, recorded_at: next.updated_at, previous_event_digest: previous, snapshot: next }; event.event_digest = envelopeDigest(event, 'event_digest'); const fd = openSync(join(dir, 'events.ndjson'), 'a', 0o600); try { appendFileSync(fd, `${canonicalJson(event)}\n`); fsyncSync(fd); } finally { closeSync(fd); } atomicJson(join(dir, 'snapshot.json'), next); return next; }
function mutate(dir, expected, callback) { return withLock(dir, () => { const loaded = load(dir); if (loaded.journal.trailing) writeFileSync(join(dir, 'events.ndjson'), loaded.journal.complete, { mode: 0o600 }); if (loaded.repair) atomicJson(join(dir, 'snapshot.json'), loaded.snapshot); if (expected !== null && loaded.snapshot.revision !== expected) throw new LedgerError(`revision conflict: expected ${expected}, actual ${loaded.snapshot.revision}`); if (loaded.snapshot.skill_provenance.content_digest !== skillContentDigest()) throw new LedgerError('skill_drift：必须 re-contract'); const result = callback(loaded.snapshot); return persist(dir, result.snapshot, result.kind); }); }

const CLI_SPEC = {
  capabilities: { values: [], flags: ['json'] }, init: { values: ['contract', 'state-root', 'ledger-id'], flags: ['allow-repository-state'] },
  'add-node': { values: ['ledger', 'input', 'expected-revision'], flags: [] }, 'add-edge': { values: ['ledger', 'input', 'expected-revision'], flags: [] },
  'dispatch-record': { values: ['ledger', 'node', 'input', 'expected-revision'], flags: [] }, update: { values: ['ledger', 'node', 'input', 'expected-revision'], flags: [] },
  attach: { values: ['ledger', 'node', 'type', 'input', 'expected-revision'], flags: [] }, 'batch-init': { values: ['ledger', 'input', 'expected-revision'], flags: [] },
  'batch-record': { values: ['ledger', 'batch', 'input', 'expected-revision'], flags: [] }, 'batch-status': { values: ['ledger', 'batch'], flags: [] }, 'batch-fuse': { values: ['ledger', 'batch'], flags: [] },
  'record-reflection': { values: ['ledger', 'input', 'expected-revision'], flags: [] }, 'propose-improvement': { values: ['ledger', 'reflection', 'input', 'expected-revision'], flags: [] },
  status: { values: ['ledger'], flags: [] }, inspect: { values: ['ledger'], flags: [] }, rebuild: { values: ['ledger', 'expected-revision'], flags: [] }, doctor: { values: ['ledger'], flags: [] },
};
function parseCli(argv) { const command = argv[0] ?? ''; const spec = CLI_SPEC[command]; if (!spec) throw new LedgerError('未知 ledger 命令'); const options = {}; const flags = new Set(); for (let i = 1; i < argv.length; i += 1) { const token = argv[i]; if (!token.startsWith('--')) throw new LedgerError(`未知位置参数 ${token}`); const name = token.slice(2); if (spec.flags.includes(name)) { if (argv[i + 1] !== undefined && !argv[i + 1].startsWith('--')) throw new LedgerError(`--${name} 不接受值`); flags.add(name); } else if (spec.values.includes(name)) { if (argv[i + 1] === undefined || argv[i + 1].startsWith('--')) throw new LedgerError(`--${name} 缺少值`); options[name] = argv[++i]; } else throw new LedgerError(`未知选项: --${name}`); } return { command, options, flags }; }
function req(options, name) { if (!options[name]) throw new LedgerError(`缺少 --${name}`); return options[name]; }
function revision(options) { if (options['expected-revision'] === undefined) return null; const value = Number(options['expected-revision']); if (!Number.isInteger(value) || value < 0) throw new LedgerError('expected-revision 无效'); return value; }

function init(options, flags) {
  const contract = validateContract(readJson(req(options, 'contract')));
  const binding = contract.skill_set.find((item) => item.name === 'orchestrate-subagents');
  if (!binding || binding.content_digest !== skillContentDigest()) throw new LedgerError('Task Contract 未冻结当前 orchestrate-subagents content digest');
  const root = resolve(options['state-root'] ?? join(tmpdir(), 'orchestration-ledger-state')); const repository = contract.environment.repository;
  if (repository && repository !== 'none' && existsSync(repository) && inside(root, repository) && !flags.has('allow-repository-state')) throw new LedgerError('state root 位于业务仓库内');
  mkdirSync(join(root, 'ledgers'), { recursive: true, mode: 0o700 }); const id = options['ledger-id'] ?? randomUUID(); if (!/^[A-Za-z0-9._-]+$/u.test(id)) throw new LedgerError('ledger-id 无效'); const dir = join(root, 'ledgers', id); mkdirSync(dir, { mode: 0o700 }); const now = new Date().toISOString();
  const snapshot = { schema_version: 1, runtime_version: '1.0.0', ledger_id: id, revision: 0, contract_digest: contract.contract_digest, nodes: {}, edges: [], attachments: [], batches: {}, reflection_refs: [], improvement_proposal_refs: [], skill_provenance: { name: 'orchestrate-subagents', version: '1.0.0', content_digest: skillContentDigest() }, created_at: now, updated_at: now };
  writeNew(join(dir, 'contract.json'), contract); const initialEvent = { schema_version: 1, revision: 0, kind: 'initialized', recorded_at: now, previous_event_digest: null, snapshot }; initialEvent.event_digest = envelopeDigest(initialEvent, 'event_digest'); writeFileSync(join(dir, 'events.ndjson'), `${canonicalJson(initialEvent)}\n`, { flag: 'wx', mode: 0o600 }); atomicJson(join(dir, 'snapshot.json'), snapshot); return { ledger_id: id, ledger_dir: dir, revision: 0 };
}

function cycle(nodes, edges) { const adj = new Map(Object.keys(nodes).map((id) => [id, []])); for (const edge of edges) adj.get(edge.from)?.push(edge.to); const visiting = new Set(), done = new Set(); const visit = (id) => { if (visiting.has(id)) return true; if (done.has(id)) return false; visiting.add(id); for (const next of adj.get(id) ?? []) if (visit(next)) return true; visiting.delete(id); done.add(id); return false; }; return [...adj.keys()].some(visit); }
function addNode(options) { const dir = realpathSync(req(options, 'ledger')); const input = readJson(req(options, 'input')); const contract = validateContract(readJson(join(dir, 'contract.json'))); return mutate(dir, revision(options), (snapshot) => { if (!/^[A-Za-z0-9._-]+$/u.test(input.node_id ?? '') || snapshot.nodes[input.node_id]) throw new LedgerError('node_id 无效或重复'); if (!['scout', 'worker', 'critic', 'judge'].includes(input.role ?? 'worker')) throw new LedgerError('node role 无效'); const permissions = input.permissions ?? { mode: 'read_only', writable_paths: [] }; if (!['read_only', 'write'].includes(permissions.mode) || !Array.isArray(permissions.writable_paths) || permissions.writable_paths.some((path) => typeof path !== 'string' || !path || isAbsolute(path) || path.split('/').includes('..'))) throw new LedgerError('node permissions 无效'); if (contract.permissions.mode === 'read_only' && (permissions.mode !== 'read_only' || permissions.writable_paths.length)) throw new LedgerError('node permissions 超出只读合同'); if (permissions.mode === 'write' && permissions.writable_paths.some((path) => !contract.permissions.writable_paths.some((allowed) => path === allowed || path.startsWith(`${allowed.replace(/\/$/u, '')}/`)))) throw new LedgerError('node writable_paths 超出合同边界'); const node = { node_id: input.node_id, objective: String(input.objective ?? ''), role: input.role ?? 'worker', required: input.required !== false, state: 'pending', permissions, dependencies: [], dispatch: null, stable_outputs: [], evidence: [], created_at: new Date().toISOString(), updated_at: new Date().toISOString() }; if (!node.objective) throw new LedgerError('node objective 不能为空'); return { snapshot: { ...snapshot, nodes: { ...snapshot.nodes, [node.node_id]: node } }, kind: 'node_added' }; }); }
function addEdge(options) { const dir = realpathSync(req(options, 'ledger')); const input = readJson(req(options, 'input')); return mutate(dir, revision(options), (snapshot) => { if (!snapshot.nodes[input.from] || !snapshot.nodes[input.to] || input.from === input.to || !['dependency', 'barrier'].includes(input.kind)) throw new LedgerError('edge 无效'); const edge = { from: input.from, to: input.to, kind: input.kind }; const edges = [...snapshot.edges, edge]; if (cycle(snapshot.nodes, edges)) throw new LedgerError('任务图不能形成环'); const target = { ...snapshot.nodes[input.to], dependencies: [...new Set([...snapshot.nodes[input.to].dependencies, input.from])] }; return { snapshot: { ...snapshot, edges, nodes: { ...snapshot.nodes, [input.to]: target } }, kind: 'edge_added' }; }); }
function dispatchRecord(options) { const dir = realpathSync(req(options, 'ledger')); const input = readJson(req(options, 'input')); const nodeId = req(options, 'node'); return mutate(dir, revision(options), (snapshot) => { const node = snapshot.nodes[nodeId]; if (!node || node.state !== 'pending') throw new LedgerError('只有 pending node 可登记 dispatch'); if (![input.worker_id, input.model, input.reasoning_effort].every((value) => typeof value === 'string' && value.trim() && !/[\r\n]/u.test(value))) throw new LedgerError('dispatch 缺 worker/model/effort 或含非法换行'); if (node.dependencies.some((id) => snapshot.nodes[id].state !== 'passed')) throw new LedgerError('依赖/barrier 尚未通过'); const next = { ...node, state: 'running', dispatch: input, updated_at: new Date().toISOString() }; return { snapshot: { ...snapshot, nodes: { ...snapshot.nodes, [nodeId]: next } }, kind: 'node_dispatched' }; }); }
function update(options) { const dir = realpathSync(req(options, 'ledger')); const input = readJson(req(options, 'input')); const nodeId = req(options, 'node'); return mutate(dir, revision(options), (snapshot) => { const node = snapshot.nodes[nodeId]; if (!node || !NODE_STATES.has(input.state)) throw new LedgerError('node/state 无效'); if (input.state === 'passed' && node.stable_outputs.length === 0) throw new LedgerError('实现节点没有稳定交付物，不能 passed'); const next = { ...node, state: input.state, checkpoint: input.checkpoint ?? null, reason: input.reason ?? null, updated_at: new Date().toISOString() }; return { snapshot: { ...snapshot, nodes: { ...snapshot.nodes, [nodeId]: next } }, kind: `node_${input.state}` }; }); }
function attach(options) { const dir = realpathSync(req(options, 'ledger')); const input = readJson(req(options, 'input')); const nodeId = req(options, 'node'); const type = req(options, 'type'); if (!['worktree', 'artifact', 'evidence', 'loop', 'report'].includes(type)) throw new LedgerError('attachment type 无效'); return mutate(dir, revision(options), (snapshot) => { if (!snapshot.nodes[nodeId]) throw new LedgerError('node 不存在'); const digest = sha256(Buffer.from(canonicalJson(input), 'utf8')); mkdirSync(join(dir, 'attachments'), { recursive: true, mode: 0o700 }); const ref = `attachments/${digest.slice(7)}.json`; if (existsSync(join(dir, ref))) { if (canonicalJson(readJson(join(dir, ref))) !== canonicalJson(input)) throw new LedgerError('attachment digest collision'); } else writeNew(join(dir, ref), input); const entry = { attachment_id: randomUUID(), node_id: nodeId, type, digest, ref }; const node = { ...snapshot.nodes[nodeId], stable_outputs: ['artifact', 'evidence', 'loop', 'report'].includes(type) ? [...snapshot.nodes[nodeId].stable_outputs, entry] : snapshot.nodes[nodeId].stable_outputs, evidence: type === 'evidence' ? [...snapshot.nodes[nodeId].evidence, entry] : snapshot.nodes[nodeId].evidence }; return { snapshot: { ...snapshot, attachments: [...snapshot.attachments, entry], nodes: { ...snapshot.nodes, [nodeId]: node } }, kind: 'attachment_added' }; }); }

function batchInit(options) { const dir = realpathSync(req(options, 'ledger')); const input = readJson(req(options, 'input')); return mutate(dir, revision(options), (snapshot) => { if (!input.batch_id || snapshot.batches[input.batch_id] || !Array.isArray(input.loop_ids) || !input.loop_ids.length) throw new LedgerError('batch 输入无效'); const batch = { batch_id: input.batch_id, loop_ids: [...new Set(input.loop_ids)], mode: input.mode ?? 'ordered', limits: { max_failures: Number(input.limits?.max_failures ?? input.loop_ids.length), consecutive_identical_signature: Number(input.limits?.consecutive_identical_signature ?? 3) }, records: [], state: 'active', fuse: null, created_at: new Date().toISOString() }; if (!Number.isInteger(batch.limits.max_failures) || !Number.isInteger(batch.limits.consecutive_identical_signature) || batch.limits.max_failures <= 0 || batch.limits.consecutive_identical_signature <= 0) throw new LedgerError('batch limits 无效'); return { snapshot: { ...snapshot, batches: { ...snapshot.batches, [batch.batch_id]: batch } }, kind: 'batch_initialized' }; }); }
export function evaluateBatchFuse(batch) { const failures = batch.records.filter((item) => item.state === 'stopped'); const signature = failures.at(-1)?.failure_key ?? null; let consecutive = 0; if (signature) for (let i = batch.records.length - 1; i >= 0 && batch.records[i].state === 'stopped' && batch.records[i].failure_key === signature; i -= 1) consecutive += 1; if (failures.length >= batch.limits.max_failures) return { kind: 'max_failures', failures: failures.length }; if (signature && consecutive >= batch.limits.consecutive_identical_signature) return { kind: 'identical_failure_fuse', failure_key: signature, consecutive }; return null; }
function batchRecord(options) { const dir = realpathSync(req(options, 'ledger')); const input = readJson(req(options, 'input')); const id = req(options, 'batch'); return mutate(dir, revision(options), (snapshot) => { const batch = snapshot.batches[id]; if (!batch || batch.state !== 'active' || !batch.loop_ids.includes(input.loop_id) || batch.records.some((item) => item.loop_id === input.loop_id) || !['completed', 'stopped'].includes(input.state)) throw new LedgerError('batch record 无效或重放'); const records = [...batch.records, { loop_id: input.loop_id, state: input.state, failure_key: input.state === 'stopped' ? input.failure_key ?? null : null, result_ref: input.result_ref ?? null, recorded_at: new Date().toISOString() }]; let next = { ...batch, records }; const fuse = evaluateBatchFuse(next); if (fuse) next = { ...next, state: 'fused', fuse }; else if (records.length === batch.loop_ids.length) next = { ...next, state: 'completed' }; return { snapshot: { ...snapshot, batches: { ...snapshot.batches, [id]: next } }, kind: fuse ? 'batch_fused' : 'batch_recorded' }; }); }
function batchStatus(options) { const snapshot = load(realpathSync(req(options, 'ledger'))).snapshot; const batch = snapshot.batches[req(options, 'batch')]; if (!batch) throw new LedgerError('batch 不存在'); return batch; }
function batchFuse(options) { const batch = batchStatus(options); return { batch_id: batch.batch_id, state: batch.state, fuse: batch.fuse ?? evaluateBatchFuse(batch) }; }

function redact(value) { return String(value ?? '').replace(/\bBearer\s+\S+/giu, 'Bearer [REDACTED]').replace(/\/(?:Users|home)\/[^\s"']+/gu, '[LOCAL_PATH]'); }
function recordReflection(options) { const dir = realpathSync(req(options, 'ledger')); const input = readJson(req(options, 'input')); return mutate(dir, revision(options), (snapshot) => { if (!['contract_gap', 'skill_gap', 'verification_gap', 'tool_gap', 'environment_gap', 'false_positive', 'false_negative', 'inefficiency'].includes(input.classification)) throw new LedgerError('reflection classification 无效'); const events = readJournal(dir).events; const event = events.at(-1); const eventDigest = sha256(Buffer.from(canonicalJson(event), 'utf8')); const value = { schema_version: 1, reflection_id: randomUUID(), trigger: input.trigger ?? 'unexpected_outcome', scope: { contract_digest: snapshot.contract_digest }, affected_skill: snapshot.skill_provenance, classification: input.classification, observation: redact(input.observation), evidence_refs: [{ type: 'event', id: `events.ndjson#revision=${event.revision}`, digest: eventDigest }], impact: input.impact ?? 'medium', confidence: 'high', recommended_disposition: input.recommended_disposition ?? 'continue', recorded_at: new Date().toISOString() }; value.reflection_digest = envelopeDigest(value, 'reflection_digest'); mkdirSync(join(dir, 'reflections'), { recursive: true, mode: 0o700 }); const ref = `reflections/${value.reflection_id}.json`; writeNew(join(dir, ref), value); return { snapshot: { ...snapshot, reflection_refs: [...snapshot.reflection_refs, { reflection_id: value.reflection_id, reflection_digest: value.reflection_digest, ref }] }, kind: 'reflection_recorded' }; }); }
function propose(options) { const dir = realpathSync(req(options, 'ledger')); const input = readJson(req(options, 'input')); const reflectionId = req(options, 'reflection'); return mutate(dir, revision(options), (snapshot) => { const ref = snapshot.reflection_refs.find((item) => item.reflection_id === reflectionId); if (!ref) throw new LedgerError('Reflection 未登记'); const reflection = readJson(join(dir, ref.ref)); const value = { schema_version: 1, proposal_id: randomUUID(), target_skill: { name: 'orchestrate-subagents', based_on_version: snapshot.skill_provenance.version, based_on_digest: snapshot.skill_provenance.content_digest }, source_reflections: [{ reflection_id: reflection.reflection_id, reflection_digest: reflection.reflection_digest }], problem: { type: input.problem_type ?? 'skill_gap', evidence_refs: reflection.evidence_refs }, proposed_change: redact(input.proposed_change), affected_scope: (input.affected_scope ?? []).map(redact), counterexamples: (input.counterexamples ?? []).map(redact), validation_plan: { replay_cases: input.validation_plan?.replay_cases ?? [], regression_suites: input.validation_plan?.regression_suites ?? [], independent_review: 'required' }, lifecycle: 'proposed' }; value.proposal_digest = envelopeDigest(value, 'proposal_digest'); mkdirSync(join(dir, 'proposals'), { recursive: true, mode: 0o700 }); const path = `proposals/${value.proposal_id}.json`; writeNew(join(dir, path), value); return { snapshot: { ...snapshot, improvement_proposal_refs: [...snapshot.improvement_proposal_refs, { proposal_id: value.proposal_id, proposal_digest: value.proposal_digest, ref: path }] }, kind: 'improvement_proposed' }; }); }

function status(options) { const loaded = load(realpathSync(req(options, 'ledger'))); const nodes = Object.values(loaded.snapshot.nodes); return { ...loaded.snapshot, recovery_needed: loaded.repair, summary: { pending: nodes.filter((n) => n.state === 'pending').length, active: nodes.filter((n) => ['running', 'blocked', 'awaiting_verification'].includes(n.state)).length, terminal: nodes.filter((n) => TERMINAL_NODE_STATES.has(n.state)).length, completion_ready: nodes.filter((n) => n.required).every((n) => n.state === 'passed') } }; }
function rebuild(options) { const dir = realpathSync(req(options, 'ledger')); return withLock(dir, () => { const loaded = load(dir); const expected = revision(options); if (expected !== null && loaded.snapshot.revision !== expected) throw new LedgerError(`revision conflict: expected ${expected}, actual ${loaded.snapshot.revision}`); if (loaded.journal.trailing) writeFileSync(join(dir, 'events.ndjson'), loaded.journal.complete, { mode: 0o600 }); atomicJson(join(dir, 'snapshot.json'), loaded.snapshot); return { rebuilt: true, revision: loaded.snapshot.revision }; }); }
function doctor(options) { const dir = realpathSync(req(options, 'ledger')); const loaded = load(dir); const snapshot = loaded.snapshot; const findings = []; if (cycle(snapshot.nodes, snapshot.edges)) findings.push('graph_cycle'); for (const node of Object.values(snapshot.nodes)) { if (node.state === 'running' && !node.dispatch) findings.push(`missing_dispatch:${node.node_id}`); if (node.state === 'passed' && !node.stable_outputs.length) findings.push(`missing_stable_output:${node.node_id}`); } for (const item of snapshot.attachments) { const path = join(dir, item.ref); if (!existsSync(path) || sha256(Buffer.from(canonicalJson(readJson(path)), 'utf8')) !== item.digest) findings.push(`attachment_invalid:${item.attachment_id}`); } for (const ref of snapshot.reflection_refs) { const value = readJson(join(dir, ref.ref)); if (envelopeDigest(value, 'reflection_digest') !== value.reflection_digest || value.reflection_digest !== ref.reflection_digest) findings.push(`reflection_invalid:${ref.reflection_id}`); for (const evidence of value.evidence_refs ?? []) { const match = /^events\.ndjson#revision=(\d+)$/u.exec(evidence.id ?? ''); const event = match ? loaded.journal.events.find((item) => item.revision === Number(match[1])) : null; if (!event || sha256(Buffer.from(canonicalJson(event), 'utf8')) !== evidence.digest) findings.push(`reflection_evidence_invalid:${ref.reflection_id}`); } } for (const ref of snapshot.improvement_proposal_refs) { const value = readJson(join(dir, ref.ref)); if (value.lifecycle !== 'proposed' || envelopeDigest(value, 'proposal_digest') !== value.proposal_digest || value.proposal_digest !== ref.proposal_digest) findings.push(`proposal_invalid:${ref.proposal_id}`); } if (skillContentDigest() !== snapshot.skill_provenance.content_digest) findings.push('skill_drift'); return { healthy: !loaded.repair && !existsSync(join(dir, '.lock')) && !findings.length, recovery_needed: loaded.repair, findings }; }
function capabilities() { return { skill: 'orchestrate-subagents', runtime_version: '1.0.0', contracts: { task_contract: [1], orchestration_ledger: [1], reflection_record: [1], improvement_proposal: [1] }, features: ['task-graph', 'barriers', 'revision-lock', 'journal-rebuild', 'stable-attachments', 'batch-fuse', 'incident-reflection', 'proposed-only-improvement'], content_digest: skillContentDigest() }; }

export function main(argv = process.argv.slice(2)) { const { command, options, flags } = parseCli(argv); if (command === 'capabilities') return capabilities(); if (command === 'init') return init(options, flags); if (command === 'add-node') return addNode(options); if (command === 'add-edge') return addEdge(options); if (command === 'dispatch-record') return dispatchRecord(options); if (command === 'update') return update(options); if (command === 'attach') return attach(options); if (command === 'batch-init') return batchInit(options); if (command === 'batch-record') return batchRecord(options); if (command === 'batch-status') return batchStatus(options); if (command === 'batch-fuse') return batchFuse(options); if (command === 'record-reflection') return recordReflection(options); if (command === 'propose-improvement') return propose(options); if (command === 'status') return status(options); if (command === 'inspect') return status(options); if (command === 'rebuild') return rebuild(options); if (command === 'doctor') return doctor(options); throw new LedgerError('未知 ledger 命令'); }
function entry() { try { return realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url)); } catch { return pathToFileURL(resolve(process.argv[1] ?? '')).href === import.meta.url; } }
if (entry()) { try { process.stdout.write(`${JSON.stringify(main(), null, 2)}\n`); } catch (error) { const code = error instanceof LedgerError || error instanceof ContractError ? 'invalid_input' : 'runtime_error'; process.stderr.write(`${JSON.stringify({ error: code, message: error.message })}\n`); process.exit(code === 'invalid_input' ? 2 : 3); } }
